    version: '3'
     
    services:
        php:
            build:
                context: ./docker/php
            volumes:
                - ./:/srv/www/api
                - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            environment:
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     
        ${WEBSITE_NAME}:
            image: nginx:latest
            restart: unless-stopped
            ports:
                - 8080:80
            volumes:
                - ./:/srv/www/api
                - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            restart: unless-stopped
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.${WEBSITE_NAME}.entrypoints=http"
                - "traefik.http.routers.${WEBSITE_NAME}.rule=Host(`${WEBSITE_DOMAIN}`)"
                - "traefik.http.middlewares.${WEBSITE_NAME}-https-redirect.redirectscheme.scheme=https"
                - "traefik.http.routers.${WEBSITE_NAME}.middlewares=${WEBSITE_NAME}-https-redirect"
                - "traefik.http.routers.${WEBSITE_NAME}-secure.entrypoints=https"
                - "traefik.http.routers.${WEBSITE_NAME}-secure.rule=Host(`${WEBSITE_DOMAIN}`)"
                - "traefik.http.routers.${WEBSITE_NAME}-secure.tls=true"
                - "traefik.http.routers.${WEBSITE_NAME}-secure.tls.certresolver=http"
                - "traefik.http.routers.${WEBSITE_NAME}-secure.service=${WEBSITE_NAME}"
                - "traefik.http.services.${WEBSITE_NAME}.loadbalancer.server.port=80"
                - "traefik.docker.network=proxy"
            depends_on:
                - php
            networks:
                - proxy
                - default
     
        ${WEBSITE_NAME}-db:
            image: mysql:newest
            restart: unless-stopped
            ports:
            depends_on:
                - php
            environment:
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                MYSQL_DATABASE: ${MYSQL_DATABASE}
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            networks:
                - default
                
networks:
  proxy:
    external: true
